### ISSUE TITLE
Add the filter categories for all Letter F documentations

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [saintmalik/awesome-oss-docs#100]
Research on each documentation in the Letter F section to filter them into `Company Owned Documentation` and `Community Owned Documentation`

After getting your answer, add the category like this in the README.md file at the front of the documentation wrapped in backticks ``

e.g.
- [Amazon S3 Docs](https://docs.aws.amazon.com/s3/index.html) - Amazon Simple Storage Service (Amazon S3) is storage for the internet. You can use Amazon S3 to store and retrieve any amount of data at any time, from anywhere on the web. - `Company Owned Documentation`

**Comment by Navlos** [comment]
Can i be assigned this issue please?

**Comment by ariyoaresa** [comment]
I'ld love to be assigned this issue

**Comment by Elijah699** [comment]
@Kinz1 you can work on this.

**Comment by nobledeveloper01** [comment]
pls assign me

**Comment by Elijah699** [comment]
Closed #127
