### ISSUE TITLE
Add the filter categories for all Letter G documentations

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [saintmalik/awesome-oss-docs#101]
Research on each documentation in the Letter G section to filter them into `Company Owned Documentation` and `Community Owned Documentation`

After getting your answer, add the category like this in the README.md file at the front of the documentation wrapped in backticks ``

e.g.
- [Amazon S3 Docs](https://docs.aws.amazon.com/s3/index.html) - Amazon Simple Storage Service (Amazon S3) is storage for the internet. You can use Amazon S3 to store and retrieve any amount of data at any time, from anywhere on the web. - `Company Owned Documentation`

**Comment by Navlos** [comment]
I would love to work on this issue please.

**Comment by alaykabir** [comment]
Hey, I understand the issue I am interested in working on this. Can you please assign this to me. Waiting for your response.

**Comment by Elijah699** [comment]
@alaykabir you can work on this

**Comment by Lumetech** [comment]
i would like to work on this

**Comment by OSCA-Ado-Ekiti** [comment]
@Lumetech you can work on this

**Comment by Elijah699** [comment]
Closed #133
