### ISSUE TITLE
Add the filter categories for all Letter N and O documentations

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [saintmalik/awesome-oss-docs#105]
Research on each documentation in the Letter N and O section to filter them into `Company Owned Documentation` and `Community Owned Documentation`

After getting your answer, add the category like this in the README.md file at the front of the documentation wrapped in backticks ``

e.g.
- [Amazon S3 Docs](https://docs.aws.amazon.com/s3/index.html) - Amazon Simple Storage Service (Amazon S3) is storage for the internet. You can use Amazon S3 to store and retrieve any amount of data at any time, from anywhere on the web. - `Company Owned Documentation`

**Comment by ariyoaresa** [comment]
I'ld love to work on this

**Comment by Elijah699** [comment]
Solved #120
