### ISSUE TITLE
Add the filter categories for all SUSE, Tailwind, The Guild documentations

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [saintmalik/awesome-oss-docs#108]
Research on each documentation in the SUSE, Tailwind and The Guild section to filter them into `Company Owned Documentation` and `Community Owned Documentation`

After getting your answer, add the category like this in the README.md file at the front of the documentation wrapped in backticks ``

e.g.
- [Amazon S3 Docs](https://docs.aws.amazon.com/s3/index.html) - Amazon Simple Storage Service (Amazon S3) is storage for the internet. You can use Amazon S3 to store and retrieve any amount of data at any time, from anywhere on the web. - `Company Owned Documentation`

**Comment by ariyoaresa** [comment]
I'ld love to be assigned to this

**Comment by Elijah699** [comment]
@ariyoaresa There is still an open issue you are attending to, kindly complete it and send a PR for it. 

Then we can proceed to this, Let's go @ariyoaresa 💪

**Comment by ariyoaresa** [comment]
Am I free to work on this now?

**Comment by Elijah699** [comment]
@ariyoaresa you can work on this

**Comment by Elijah699** [comment]
Solved #115
