### ISSUE TITLE
Make Documentation Section and Card a reusable component

### ISSUE THREAD

**Issue by logboi1** [saintmalik/awesome-oss-docs#131]
I want to propose making the docSection and docCard reusable to make the code more readable and flexible for scalability. You can assign me to it

**Comment by logboi1** [comment]
@saintmalik @Elijah699

**Comment by Elijah699** [comment]
@logboi1  just work on extraction of card to a single components.

Once the filters are done the docs will be sorted alphabetically to ease mapping on the site.

**Comment by logboi1** [comment]
make a PR for it #132 @Elijah699

**Comment by Elijah699** [comment]
Solved #132
