### ISSUE TITLE
Add the filter categories for all Facebook documentations

### ISSUE THREAD

**Issue by ariyoaresa** [saintmalik/awesome-oss-docs#140]
Research on each documentation in the Twilio, Twitter and Upbound section to filter them into Company Owned Documentation and Community Owned Documentation

After getting your answer, add the category like this in the README.md file at the front of the documentation wrapped in backticks ``

e.g.

Amazon S3 Docs - Amazon Simple Storage Service (Amazon S3) is storage for the internet. You can use Amazon S3 to store and retrieve any amount of data at any time, from anywhere on the web. - Company Owned Documentation

**Comment by Lumetech** [comment]
I would like to work on this issue

**Comment by OSCA-Ado-Ekiti** [comment]
@ariyoaresa have you sent a PR for this?
