### ISSUE TITLE
Create amazon.js file and add all Amazon docs in the README.md to the file

### ISSUE THREAD

**Issue by Elijah699** [saintmalik/awesome-oss-docs#141]
1. Follow this structure to know where you will create your file:

`awesome-oss-docs/awesome-oss-docs/src/constants/docs/orderByAlphabet`

2. Add all amazon docs to the file you created,. Each docs are added in this format:

{
    title: 'Airflow Docs',
      description:
        'A platform to programmatically author, schedule, and monitor workflows.',
      projectUrl: 'https://airflow.incubator.apache.org/docs/',
      githubUrl: 'https://github.com/apache/airflow/tree/main/docs',
      owner: 'Community Owned Documentation',
},

For better insight of how the file should look like check out the [Apache File](https://github.com/saintmalik/awesome-oss-docs/blob/main/awesome-oss-docs/src/constants/docs/orderByAlphabet/apache.js)

3.  After adding all docs, Go to the `index.js` file in the docs folder, create an import of the file you added and put the name in the export default array

**Comment by wonderful-coyote** [comment]
hello kindly assign me to this... thanks

**Comment by nobledeveloper01** [comment]
assign me pls

**Comment by Elijah699** [comment]
@nobledeveloper01 you can work on this

**Comment by Elijah699** [comment]
Solved #171
