### ISSUE TITLE
Create deltalake.js file and add all DeltaLake docs in the README.md to the file

### ISSUE THREAD

**Issue by Elijah699** [saintmalik/awesome-oss-docs#146]
1. Follow this structure to know where you will create your file:

`awesome-oss-docs/awesome-oss-docs/src/constants/docs/orderByAlphabet`

2. Add all DeltaLake docs to the file you created,. Each docs are added in this format:

{
    title: 'Airflow Docs',
      description:
        'A platform to programmatically author, schedule, and monitor workflows.',
      projectUrl: 'https://airflow.incubator.apache.org/docs/',
      githubUrl: 'https://github.com/apache/airflow/tree/main/docs',
      owner: 'Community Owned Documentation',
},

For better insight of how the file should look like check out the [Apache File](https://github.com/saintmalik/awesome-oss-docs/blob/main/awesome-oss-docs/src/constants/docs/orderByAlphabet/apache.js)

3.  After adding all docs, Go to the `index.js` file in the docs folder, create an import of the file you added and put the name in the export default array

**Comment by nobledeveloper01** [comment]
pls assign me

**Comment by Elijah699** [comment]
@nobledeveloper01 you can work on this

**Comment by Elijah699** [comment]
@nobledeveloper01 are you still working on this?

**Comment by nobledeveloper01** [comment]
Yes,  you will receive my PR this evening

**Comment by Elijah699** [comment]
Solved #172
