### ISSUE TITLE
Create elastic.js file and add all Elastic docs in the README.md to the file

### ISSUE THREAD

**Issue by Elijah699** [saintmalik/awesome-oss-docs#149]
1. Follow this structure to know where you will create your file:

`awesome-oss-docs/awesome-oss-docs/src/constants/docs/orderByAlphabet`

2. Add all Elastic docs to the file you created,. Each docs are added in this format:

{
    title: 'Airflow Docs',
      description:
        'A platform to programmatically author, schedule, and monitor workflows.',
      projectUrl: 'https://airflow.incubator.apache.org/docs/',
      githubUrl: 'https://github.com/apache/airflow/tree/main/docs',
      owner: 'Community Owned Documentation',
},

For better insight of how the file should look like check out the [Apache File](https://github.com/saintmalik/awesome-oss-docs/blob/main/awesome-oss-docs/src/constants/docs/orderByAlphabet/apache.js)

3.  After adding all docs, Go to the `index.js` file in the docs folder, create an import of the file you added and put the name in the export default array

**Comment by taran1326** [comment]
Hey @Elijah699  I would like to work on this! Please assign me the issue ?

**Comment by taran1326** [comment]
Its done , I created the pull request, please accept and merge it.

**Comment by OSCA-Ado-Ekiti** [comment]
Solved #159
