### ISSUE TITLE
Create hashicorp.js file and add all HashiCorp docs in the README.md to the file

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [saintmalik/awesome-oss-docs#154]
1. Follow this structure to know where you will create your file:

`awesome-oss-docs/awesome-oss-docs/src/constants/docs/orderByAlphabet`

2. Add all HashiCorp docs to the file you created,. Each docs are added in this format:

{
    title: 'Airflow Docs',
      description:
        'A platform to programmatically author, schedule, and monitor workflows.',
      projectUrl: 'https://airflow.incubator.apache.org/docs/',
      githubUrl: 'https://github.com/apache/airflow/tree/main/docs',
      owner: 'Community Owned Documentation',
},

For better insight of how the file should look like check out the [Apache File](https://github.com/saintmalik/awesome-oss-docs/blob/main/awesome-oss-docs/src/constants/docs/orderByAlphabet/apache.js)

3.  After adding all docs, Go to the `index.js` file in the docs folder, create an import of the file you added and put the name in the export default array

**Comment by medha-ab** [comment]
I like to work on this issue, Please assign it to me.

**Comment by OSCA-Ado-Ekiti** [comment]
@medha-ab you can work on this

**Comment by Elijah699** [comment]
@medha-ab are you still working on this?

**Comment by medha-ab** [comment]
yes, will be done today.

**Comment by Elijah699** [comment]
Solved #175
