### ISSUE TITLE
Add Active Netflix OSS Docs

### ISSUE THREAD

**Issue by nishi1401** [saintmalik/awesome-oss-docs#67]
I would like to add some active Netflix Open Source Projects that have a documentation page that still accepts contributions.

- [Conductor](https://github.com/Netflix/conductor)
- [Eureka](https://github.com/Netflix/eureka)

**Comment by saintmalik** [comment]
Looks like we have Netflix OSS Docs already

**Comment by queenish001** [comment]
My bad, I overlooked that :')
Is it fine if I append these 2 to the already existing list?

**Comment by saintmalik** [comment]
> My bad, I overlooked that :') Is it fine if I append these 2 to the already existing list?

Sure, you can

**Comment by shazm12** [comment]
hi @saintmalik , can you please check my PR #69. Thanks for the opportunity, and really appreciate the work you all are doing here.

**Comment by OSCA-Ado-Ekiti** [comment]
Looks like you've closed the PR, why?

**Comment by shazm12** [comment]
Yes, sorry I closed it because it seems I had a broken link, sorry for this, but now I have made proper changes and made a PR again #70.
Sorry for the inconvenience and thank you!
