### ISSUE TITLE
Add Microsoft docs

### ISSUE THREAD

**Issue by sdwheeler** [saintmalik/awesome-oss-docs#71]
Almost all of Microsoft's documentation is open source even if the product/project being documented is not open source.

You can browse the [MicrosoftDocs](https://github.com/MicrosoftDocs?q=&type=public&language=&sort=) org to see the public repos for docs.

Here are some notable repos:

- [PowerShell-Docs](https://github.com/MicrosoftDocs/PowerShell-Docs) - this is the repo I maintain
- [azure-docs-sdk-python](https://github.com/MicrosoftDocs/azure-docs-sdk-python)
- [azure-docs-powershell](https://github.com/MicrosoftDocs/azure-docs-powershell)
- [microsoft-365-docs](https://github.com/MicrosoftDocs/microsoft-365-docs)
- [Azure-docs](https://github.com/MicrosoftDocs/Azure-docs)
- [azure-docs-cli](https://github.com/MicrosoftDocs/azure-docs-cli)

**Comment by saintmalik** [comment]
Thanks for pointing this out, will add them to the list soon, and also you doing awesome job as a maintainer @[Powershell Docs](https://github.com/MicrosoftDocs/PowerShell-Docs)

**Comment by saintmalik** [comment]
They have been added, thank you.
