### ISSUE TITLE
Split company-supported OSS projects from community ones

### ISSUE THREAD

**Issue by waldyrious** [saintmalik/awesome-oss-docs#75]
I would love to see a section dedicated to indie/community projects, since those are likely those that need documentation contributors the most, and people looking for open source projects to contribute docs to might want to look at those specifically. I know I would :)

Additionally, maybe we could also consider dividing the large projects into those that are supported by for-profit corporations, and those that are backed by organizations, non-profits and foundations focused on the open source model, e.g. Apache, RedHat, Mozilla, Wikimedia, Linux, etc.

**Comment by saintmalik** [comment]
Thats a good idea, it will make sorting easier for people, how can we proceed with that?

**Comment by waldyrious** [comment]
I would suggest having two main sections, one for community docs and one for company-backed docs, and the current sections would simply be at a lower heading level under the second section.

**Comment by saintmalik** [comment]
Thats great, mind helping with that?

**Comment by waldyrious** [comment]
I'd be happy to submit a PR once I get some free time, though to be honest, that may take a while considering my calendar for the next few weeks/months :sweat_smile:

**Comment by saintmalik** [comment]
Okay i will find away to get this done, will be free next week, hopefully

**Comment by saintmalik** [comment]
> I'd be happy to submit a PR once I get some free time, though to be honest, that may take a while considering my calendar for the next few weeks/months 😅

Pushed, please see if it meets the issue request before closing

**Comment by waldyrious** [comment]
Hmm, it seems like the changes in 95a87b0cbf4f05f31922b87dad7f508b1c71190f were reverted in de2a23bceaee9b10de272fcf02eab5f5692e0dbb?

**Comment by saintmalik** [comment]
Yeah, it was failing the linting test for ToC, have any idea on how I can go around that?

**Comment by waldyrious** [comment]
Can you link to the logs of one such failing lint run? I tried looking in https://github.com/saintmalik/awesome-oss-docs/actions, but the most recent runs there are from two months ago...

**Comment by saintmalik** [comment]
> Can you link to the logs of one such failing lint run? I tried looking in https://github.com/saintmalik/awesome-oss-docs/actions, but the most recent runs there are from two months ago...

Yeah, you are correct, the actions was implemented only for pull requests against the main branch and not for my direct push to the main branch.

I would share with you the error from my local host test.

**Comment by saintmalik** [comment]
Hello 👋 @waldyrious I think I have found what will work best for this implementation, a live website that has filters?

Check this: https://awesome-oss-docs.herokuapp.com/

**Comment by OSCA-Ado-Ekiti** [comment]
@saintmalik can i close this issue now?
