### ISSUE TITLE
UI/UX: Create a rendered web version of awesome-oss-docs

### ISSUE THREAD

**Issue by saintmalik** [saintmalik/awesome-oss-docs#80]
hello there 👋

We want to create the web interface for awesome oss docs repo.

But the data are to be splitted into company-supported OSS projects and community based OSS projects.

issue #75

**Comment by saintmalik** [comment]
> hello there 👋
> 
> We want to create the web interface for awesome oss docs repo.
> 
> But the data are to be splitted into company-supported OSS projects and community based OSS projects.

#75

**Comment by onifaithayoola** [comment]
Interested boss

**Comment by Victorayo** [comment]
Any update? @saintmalik

**Comment by OSCA-Ado-Ekiti** [comment]
Solved #86
