### ISSUE TITLE
Build a Card component for the web version of awesome-oss-docs card

### ISSUE THREAD

**Issue by saintmalik** [saintmalik/awesome-oss-docs#82]
There is a need for the web version of awesome-oss-docs, although one was created but not completed, see here: https://awesome-oss-docs.herokuapp.com/

The use of Javascript frameworks are accepted.

Building a web version can help tweak and give more space more filtering downs, in respect to this issue #75

**Comment by saintmalik** [comment]
Design in progress, will be up soon #80

**Comment by saintmalik** [comment]
@J0shcodes are you still up to pick this issue? the designs are ready

**Comment by saintmalik** [comment]
not the whole page, can you work on the card section?

**Comment by OSCA-Ado-Ekiti** [comment]
Here is the figma link: 
https://www.figma.com/file/jsRFaDirWjXPBIOZGpqg7G/Awesome-OSS-DOCS?type=design&node-id=3-8&mode=design&t=ONMpUbRon01k3gV5-0

This an image of the card below:
![Screenshot_20231004-200125_Chrome](https://github.com/saintmalik/awesome-oss-docs/assets/85078495/1f5a7a8a-260d-4b59-9fbf-7509cd765a08)

**Comment by nobledeveloper01** [comment]
can i see how the full page look like sir, to know how to structure it

**Comment by nobledeveloper01** [comment]
seen pls assign me

**Comment by nobledeveloper01** [comment]
pls assign me

**Comment by Chaos10001** [comment]
Can I get assigned to this

**Comment by OSCA-Ado-Ekiti** [comment]
@nobledeveloper01 you can check the figma link

**Comment by OSCA-Ado-Ekiti** [comment]
> Can I get assigned to this

Kindly pick another issue

**Comment by nobledeveloper01** [comment]
pls close this, it has been done

**Comment by Elijah699** [comment]
@nobledeveloper01 send in your PR

**Comment by Elijah699** [comment]
Solved #113
