### ISSUE TITLE
Dark version of awesome-oss-docs webpage design

### ISSUE THREAD

**Issue by Victorayo** [saintmalik/awesome-oss-docs#83]
Cc: @saintmalik 
Create a dark version of the awesome-oss-docs webpage design.

Check this issue for what to work on:
https://github.com/saintmalik/awesome-oss-docs/issues/80

**Comment by onifaithayoola** [comment]
Interested

**Comment by saintmalik** [comment]
assigned

**Comment by ChrixCode** [comment]
Assign this to me please
