### ISSUE TITLE
Create the header section of awesome-oss-docs web

### ISSUE THREAD

**Issue by saintmalik** [saintmalik/awesome-oss-docs#84]
Hello there 👋

we need help with creating the header section from this design here: https://www.figma.com/file/jsRFaDirWjXPBIOZGpqg7G/Untitled?node-id=0%3A1

Language to use: ReactJs

**Comment by Anuran12** [comment]
@saintmalik I would like to work on this

**Comment by SlimmyTee** [comment]
I would like to work on this

**Comment by Anuran12** [comment]
@saintmalik Hay.. Please assign me

**Comment by saintmalik** [comment]
@Anuran12 can you work on this issue instead #85 ?

**Comment by abisayo** [comment]
@saintmalik is it still open to work on?

**Comment by williamwebs** [comment]
I will like to work on this.

please assign this issue to me.

**Comment by OSCA-Ado-Ekiti** [comment]
Solved PR #94
