### ISSUE TITLE
Create the search and filter section of awesome-oss-docs web

### ISSUE THREAD

**Issue by saintmalik** [saintmalik/awesome-oss-docs#85]
Hello there 👋

we need help with creating the search and filtering section from this design here: https://www.figma.com/file/jsRFaDirWjXPBIOZGpqg7G/Untitled?node-id=0%3A1

Language to use: ReactJs

**Comment by Anuran12** [comment]
@saintmalik i would like to work on this

**Comment by saintmalik** [comment]
assigned

**Comment by Anuran12** [comment]
@saintmalik  hey where is the folder of the website? i mean where should i add the code?

**Comment by saintmalik** [comment]
just push to the root folder, it ill be rearranged

**Comment by saintmalik** [comment]
hell there, still working on this ?

**Comment by abisayo** [comment]
@saintmalik still open to work on??

**Comment by Samson063** [comment]
pls can you assign this task to me?

**Comment by OSCA-Ado-Ekiti** [comment]
@Samson063 you can work on this.

**Comment by wonderful-coyote** [comment]
I would like to work on this…

**Comment by Elijah699** [comment]
@wonderful-coyote you can work on this
