### ISSUE TITLE
Create a Vitejs setup for the awesome OSS Docs

### ISSUE THREAD

**Issue by Elijah699** [saintmalik/awesome-oss-docs#89]
Clone this repository to your local machine and bootstrap a React template with Vitejs in the root folder.

**Comment by Petsamuel** [comment]
please assign task to me

**Comment by nobledeveloper01** [comment]
please assign this task to me

**Comment by Elijah699** [comment]
@Petsamuel kindly pick another issue.

**Comment by nobledeveloper01** [comment]
should i install and styling library like tailwind.css?

**Comment by Elijah699** [comment]
@nobledeveloper01 yes you can install it

**Comment by AlbertAdekanye** [comment]
assign task to me please

**Comment by nobledeveloper01** [comment]
i already sent a PR but it failed due to an error in READme.md pls help me in correcting that. thanks

**Comment by nobledeveloper01** [comment]
![image](https://github.com/saintmalik/awesome-oss-docs/assets/130615994/35a74826-3f43-4c6a-9f58-539d948df22a)
this is the error sir

**Comment by nobledeveloper01** [comment]
and this are the details of the errors
![image](https://github.com/saintmalik/awesome-oss-docs/assets/130615994/67f499aa-1919-49cd-b47b-ba0fe52afd68)
![image](https://github.com/saintmalik/awesome-oss-docs/assets/130615994/0ac1c628-b152-4607-ba2c-2f811ac9159b)

**Comment by saintmalik** [comment]
Please ignore those of errors and proceed

**Comment by nobledeveloper01** [comment]
ok boss

**Comment by nobledeveloper01** [comment]
so whats the next thing to do

**Comment by saintmalik** [comment]
Yes, but resolve the conflicting commits

**Comment by nobledeveloper01** [comment]
sorry boss, can you pls point my attention to that is because I cant see anything from my end here

**Comment by OSCA-Ado-Ekiti** [comment]
Solved #92
