### ISSUE TITLE
Workflow: Write the linting workflow

### ISSUE THREAD

**Issue by Elijah699** [saintmalik/awesome-oss-docs#90]
Hello there, here is an issue to write the github workflow that checks the code to see if it follows the laid down rules, hence on every pull request it runs the linting check. e.g husky and prettier setup

**Comment by Petsamuel** [comment]
assign to me

**Comment by OSCA-Ado-Ekiti** [comment]
@Petsamuel  you can work on this issue, it should be in the awesome oss docs folder.

**Comment by OSCA-Ado-Ekiti** [comment]
@Petsamuel kindly acknowledge you have seen this and there is progress on it

**Comment by Petsamuel** [comment]
See and I'm working on it

**Comment by Elijah699** [comment]
Solved #112
