### ISSUE TITLE
Add the filter categories for all Airbnb and Amazon documentations

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [saintmalik/awesome-oss-docs#96]
Research on each documentation in the Airbnb and Amazon section to filter them into `Company Owned Documentation` and `Community Owned Documentation`

After getting your answer, add the category like this in the README.md file at the front of the documentation wrapped in backticks ``

e.g.
- [Amazon S3 Docs](https://docs.aws.amazon.com/s3/index.html) - Amazon Simple Storage Service (Amazon S3) is storage for the internet. You can use Amazon S3 to store and retrieve any amount of data at any time, from anywhere on the web. - `Company Owned Documentation`

**Comment by DanielAgbeni** [comment]
I can handle this

**Comment by OSCA-Ado-Ekiti** [comment]
@DanielAgbeni you can work on this and carefully read the description please

**Comment by DanielAgbeni** [comment]
I will start working right away

**Comment by Elijah699** [comment]
Solved #117
