### ISSUE TITLE
Add the filter categories for Apache, Apple and Bridgecrew documentations

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [saintmalik/awesome-oss-docs#97]
Research on each documentation in the Apache. Apple and Bridgecrew section to filter them into `Company Owned Documentation` and `Community Owned Documentation`

After getting your answer, add the category like this in the README.md file at the front of the documentation wrapped in backticks ``

e.g.
- [Amazon S3 Docs](https://docs.aws.amazon.com/s3/index.html) - Amazon Simple Storage Service (Amazon S3) is storage for the internet. You can use Amazon S3 to store and retrieve any amount of data at any time, from anywhere on the web. - `Company Owned Documentation`

**Comment by SyntaxSmiler03** [comment]
Hello @OSCA-Ado-Ekiti,
Could you please assign this task to me? I'm interested in working on it.
Thank you!

**Comment by OSCA-Ado-Ekiti** [comment]
@SyntaxSmiler03 you can work on this.

**Comment by Elijah699** [comment]
@SyntaxSmiler03 are you still working on this?

**Comment by ariyoaresa** [comment]
@Elijah699 If you feel like you need another person to work on this, please consider me

**Comment by Kinz1** [comment]
Can you assign this to me?

**Comment by ariyoaresa** [comment]
@Elijah699 Can I please be assigned to this issue

**Comment by Elijah699** [comment]
@ariyoaresa you can work on this.

**Comment by Elijah699** [comment]
Sorted #135
