### ISSUE TITLE
Add the filter categories for Confluent and Cryptocurrencies documentations

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [saintmalik/awesome-oss-docs#98]
Research on each documentation in the Confluent and Cryptocurrencies section to filter them into `Company Owned Documentation` and `Community Owned Documentation`

After getting your answer, add the category like this in the README.md file at the front of the documentation wrapped in backticks ``

e.g.
- [Amazon S3 Docs](https://docs.aws.amazon.com/s3/index.html) - Amazon Simple Storage Service (Amazon S3) is storage for the internet. You can use Amazon S3 to store and retrieve any amount of data at any time, from anywhere on the web. - `Company Owned Documentation`

**Comment by nobledeveloper01** [comment]
assign me to this

**Comment by nobledeveloper01** [comment]
assign me to this

**Comment by nobledeveloper01** [comment]
pls assign me

**Comment by nobledeveloper01** [comment]
pls assign me

**Comment by nobledeveloper01** [comment]
pls assign me

**Comment by nobledeveloper01** [comment]
pls assign me

**Comment by Chaos10001** [comment]
will love to work on this

**Comment by Elijah699** [comment]
@Chaos10001 kindly send in a PR for the current issue you are working on then you can be assigned to this. Let's go 💪

**Comment by Chaos10001** [comment]
Have sent a PR on it chief @Elijah699

**Comment by Elijah699** [comment]
@Chaos10001 you can work on this.

Kindly download the markdown lint extension by David Anson on Vscode to format the README.md file properly after you add your changes.

Well done chief

**Comment by Chaos10001** [comment]
Will do just that chief...

**Comment by Elijah699** [comment]
Solved #130

**Comment by Elijah699** [comment]
Solved #130
